.MODEL SMALL
.DATA
     MSG  DB 10,13,"ENTER A NUMBER:$"
     MSG1 DB 10,13, "NUMBER IS EVEN.$"       ;FOR PRINT MESSAGE
     MSG2 DB 10,13, "NUMBER IS ODD.$"     

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX,MSG
    MOV AH,9
    INT 21H 
    
    MOV AH,1     ;INPUT A VALUE
    INT 21H  
    
    MOV BL,2     ;STORE IN BL 2
    DIV BL       ;STORE REMINDER AFTER DIVISION 
    CMP AH,0     ;COMPATE WITH 0 AND REMINDER
    
    JE EVEN            ;IF REMINDER IS EQUALE TO 0 THEN JUMP TO EVEN STATEMENT
        LEA DX,MSG2    ;ELSE PRINT THIS MESSAGE
        MOV AH,9
        INT 21H
    
    MOV AH,4CH         ;IF ELSE STATEMENT IS TRUE THEN INTERRUPT BY THIS STATEMENT
    INT 21H    
    
    EVEN:              ;EVEN SEGMENT 
        LEA DX,MSG1
        MOV AH,9
        INT 21H
        
    
MAIN ENDP