.MODEL SMALL
.DATA
   A DB 5      ;STORE  5 INTO AL REGISTER
   B DB 6      ;STORE  6 INTO BL REGISTER
   MSG DB "PROD = $"  ;FOR PRINT

.CODE
NIROB PROC
    
    MOV AX,@DATA     
    MOV DS,AX
    
    MOV AL,A
    MOV BL,B    
    
    MUL BL     ;MULTIPLY TWO NUMBER AND IT STORE LIKE AX=AL X BL(30=5 X 6)
    AAM        ;ASCHII ADJUST MULTIPLICATION
    MOV CH,AH  ;STORE AH(FIRST PART OF AX) INTO CH REGISTER
    ADD CH,48  ;ADD 48 WITH CH FOR GET EXACT VALUE
    MOV CL,AL  ;STORE AL(SECOND PART OF AX) INTO CL REGISTER
    ADD CL,48  ;ADD 48 WITH CL FOR GET EXACT VALUE
    
    LEA DX,MSG
    MOV AH,9    ;FOR PRINT MESSAGE
    INT 21H
    
    MOV AH,2
    MOV DL,CH  ;FOR PRINT FISRT PART 3 
    INT 21H   
    
    MOV AH,2
    MOV DL,CL   ;FOR PRINT SECOND PART 0
    INT 21H
    
    
NIROB ENDP
END
